#!/usr/bin/env node
/**
 * 把 gateway/ui 拷进 src-tauri/ui/，打进桌面包。壳子用 satu:// 协议从这儿发界面（main.rs 的
 * serve_ui）。开发时（tauri dev）不用拷——壳子直接读仓库里的 gateway/ui。
 */
import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const desktop = dirname(dirname(fileURLToPath(import.meta.url)))
const root = dirname(desktop)
const out = join(desktop, 'src-tauri', 'ui')
rmSync(out, { recursive: true, force: true })
mkdirSync(out, { recursive: true })
// 拷完 gateway/ui 再补占位 README，和 runtime/ 一样让 tauri-build 的通配永远有东西可命中。
cpSync(join(root, 'gateway', 'ui'), out, { recursive: true })
writeFileSync(join(out, 'README.txt'), 'Generated by `pnpm --filter satuwork-desktop prepare:ui` before packaging. Source: gateway/ui.\n')
console.log(`desktop: 界面已拷到 ${out}`)
