#!/usr/bin/env node
import { appendFileSync, copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

const desktop = dirname(dirname(fileURLToPath(import.meta.url)))
const root = dirname(desktop)
const runtime = join(desktop, 'src-tauri', 'runtime')
const bot = join(runtime, 'bot')
rmSync(runtime, { recursive: true, force: true })
mkdirSync(bot, { recursive: true })
writeFileSync(join(runtime, 'README.txt'), 'Generated by `pnpm --filter satuwork-desktop prepare:runtime` before packaging.\n')

function logSummary(msg) {
  console.error(msg)
  if (process.env.GITHUB_STEP_SUMMARY) {
    try {
      appendFileSync(process.env.GITHUB_STEP_SUMMARY, msg + '\n')
    } catch {}
  }
}

const deployed = spawnSync('pnpm', ['--filter', 'satuwork', 'deploy', '--legacy', bot], {
  cwd: root,
  stdio: 'inherit',
  shell: process.platform === 'win32',
})
if (deployed.status !== 0) {
  logSummary(`prepare-runtime: pnpm deploy 失败，status=${deployed.status}, error=${deployed.error}`)
  process.exit(deployed.status || 1)
}

// 走相对路径在 runtime 目录内执行 tar，避开 Windows 下 GNU tar 对带盘符绝对路径（如 D:\...）误判为远程机器并报 exit code 2 的问题
const packed = spawnSync('tar', ['-czf', 'bot.tgz', '-C', 'bot', '.'], {
  cwd: runtime,
  stdio: 'inherit',
})
if (packed.status !== 0) {
  logSummary(`prepare-runtime: tar 失败，status=${packed.status}, error=${packed.error}`)
  process.exit(packed.status || 1)
}
rmSync(bot, { recursive: true, force: true })
const version = createHash('sha256').update(readFileSync(join(runtime, 'bot.tgz'))).digest('hex')
writeFileSync(join(runtime, 'VERSION'), version + '\n')

const node = process.platform === 'win32'
  ? join(runtime, 'node', 'node.exe')
  : join(runtime, 'node', 'bin', 'node')
mkdirSync(dirname(node), { recursive: true })
copyFileSync(process.execPath, node)
console.log(`desktop: 本地 Bot 运行时已准备到 ${resolve(runtime)}`)
