#!/usr/bin/env node
/**
 * 把 gateway/ui 拷进 src-tauri/ui/，作为 frontendDist 打进手机包（lib.rs 的 serve_ui 从
 * asset_resolver 里发）。debug 构建（tauri ios dev）不用拷——壳子直接读仓库里的 gateway/ui。
 * 和 desktop/scripts/prepare-ui.mjs 是同一件事。
 */
import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const mobile = dirname(dirname(fileURLToPath(import.meta.url)))
const root = dirname(mobile)
const out = join(mobile, 'src-tauri', 'ui')
rmSync(out, { recursive: true, force: true })
mkdirSync(out, { recursive: true })
cpSync(join(root, 'gateway', 'ui'), out, { recursive: true })
writeFileSync(join(out, 'README.txt'), 'Generated by `pnpm --filter satuwork-mobile prepare:ui` before packaging. Source: gateway/ui.\n')
console.log(`mobile: 界面已拷到 ${out}`)
