/**
 * 装机脚本。`GET /install-manager.sh` 把它按请求的 Host 填好之后原样吐出去。
 *
 * 目标是一条命令：
 *
 *   curl -fsSL https://gw/install-manager.sh | sudo bash -s -- --code SW-XXXX-XXXX
 *
 * 之后这台 Debian 上不用再敲任何东西——建席位账号、装桌面栈、起 bot、以后自己
 * 升级，全归管家。
 *
 * 脚本本身要能重复跑：换过配对码、或者管家版本升不动了，重跑一次就是修复手段。
 *
 * **带不带 `--code`，重跑的语义不一样。** 不带码 = 只重装、身份不动；带码 = 按这张码
 * 重配。后者原来是失效的：管家看见本地已有 manager.json 就直接说「已配对」，配对码看
 * 都不看，而这个脚本判成功的唯一依据又是「那个文件在不在」——于是机器在平台上被删掉
 * 之后带新码重跑，脚本一秒打印 Paired，Gateway 那边一次 `POST /machines/pair` 都没收到，
 * 管家拿着一个已经不存在的 machineId 一直发心跳收 401（401 被刻意设计成不据此自毁），
 * 人只看到界面上始终没有这台机器。两处一起改：管家那边见码就用码（见 manager/src/
 * pair.ts），这边改成等 manager.json 的内容**变掉**——重配一定会换票，所以内容一定会变。
 *
 * **脚本内容全部英文。** 它跑在别人的服务器上，那儿的 locale 可能是 `C`——中文
 * 输出会变成一屏乱码，而这恰好是装机出问题时唯一能看的东西。仓库里其余地方的
 * 注释仍然用中文：那些不会打到那台机器的终端上。
 */

/** 管家包里带 tsx，不带 Node。这是运行 `node:sqlite` 和现代语法的下限。 */
const NODE_MAJOR = 24

export function installScript(gatewayUrl: string): string {
  return `#!/bin/bash
# Satuwork machine manager installer. Generated by ${gatewayUrl}.
#
#   curl -fsSL ${gatewayUrl}/install-manager.sh | sudo bash -s -- --code SW-XXXX-XXXX
#
# Safe to re-run: it reinstalls and restarts the service. Without --code an
# already paired machine keeps its identity; with --code it re-pairs using that
# code, and falls back to the old identity if the code is used up or expired.
set -euo pipefail

GATEWAY_URL=${JSON.stringify(gatewayUrl)}
CODE=""
PORT=8443
while [ $# -gt 0 ]; do
  case "$1" in
    --code) CODE="\${2:-}"; shift 2 ;;
    --port) PORT="\${2:-8443}"; shift 2 ;;
    --gateway) GATEWAY_URL="\${2:-}"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ "$(id -u)" != 0 ]; then echo "must run as root (prefix with sudo)" >&2; exit 1; fi
if [ -z "$CODE" ] && [ ! -f /etc/satuwork/manager.json ]; then
  echo "--code is required: generate one on the company page in the Gateway console" >&2
  exit 2
fi

echo "==> Checking Node"
NEED_NODE=1
if command -v node >/dev/null 2>&1; then
  CUR="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)"
  if [ "$CUR" -ge ${NODE_MAJOR} ]; then NEED_NODE=0; fi
fi
if [ "$NEED_NODE" = 1 ]; then
  echo "    installing Node ${NODE_MAJOR}"
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl gnupg
  curl -fsSL https://deb.nodesource.com/setup_${NODE_MAJOR}.x | bash -
  DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
fi
# The unit hardcodes /usr/bin/node: systemd does not consult PATH, so a Node
# installed elsewhere fails with 203/EXEC.
if [ ! -x /usr/bin/node ]; then ln -sf "$(command -v node)" /usr/bin/node; fi

echo "==> Downloading the manager"
apt-get install -y curl tar >/dev/null 2>&1 || true
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
# Re-running this script on an already-paired machine is the documented repair path
# (manager/README.md): it restores a missing satuwork-worker unit, an interrupted
# self-upgrade, or a changed address. Such a machine has no pairing code any more, so
# fetch the package with the machine token that pairing wrote to manager.json. Without
# this branch the re-run dies on a 401 right here and "just run it again" is a promise
# the script cannot keep.
# The Gateway either streams the package or 302s to its GitHub Release; either way the
# checksum rides on the Gateway's own response as x-bot-sha256. -D keeps every hop's
# headers so it survives the redirect. curl does not carry our Authorization header to
# another host when following a redirect, so the machine token stays with the Gateway.
if [ -n "$CODE" ]; then
  curl -fsSL -D "$TMP/headers" "$GATEWAY_URL/manager/release?code=$CODE" -o "$TMP/manager.tgz"
else
  MT="$(node -p 'JSON.parse(require("fs").readFileSync("/etc/satuwork/manager.json","utf8")).token' 2>/dev/null || true)"
  if [ -z "$MT" ]; then
    echo "no --code, and /etc/satuwork/manager.json has no machine token to fall back on" >&2
    exit 2
  fi
  # The Gateway reads the machine token from Authorization (lib/guards.ts requireMachine);
  # x-satuwork-machine is the manager's own convention and does not apply here.
  curl -fsSL -D "$TMP/headers" -H "authorization: Bearer $MT" "$GATEWAY_URL/manager/release" -o "$TMP/manager.tgz"
fi
# This package runs as root: no checksum, no install.
WANT="$(awk -F': *' 'tolower($1) == "x-bot-sha256" { print $2; exit }' "$TMP/headers" | tr -d '[:space:]')"
if [ -z "$WANT" ]; then echo "the Gateway sent no x-bot-sha256 for the manager package, refusing to install" >&2; exit 1; fi
GOT="$(sha256sum "$TMP/manager.tgz" | cut -d' ' -f1)"
if [ "$GOT" != "$WANT" ]; then echo "manager package checksum mismatch: got $GOT, want $WANT" >&2; exit 1; fi
STAGED=/opt/satuwork/manager/releases/staged.$$
mkdir -p "$STAGED"
tar -xzf "$TMP/manager.tgz" -C "$STAGED"
[ -f "$STAGED/bin/satuwork-manager.mjs" ] || { echo "package has no bin/satuwork-manager.mjs" >&2; exit 1; }
VERSION="$(cat "$STAGED/VERSION" 2>/dev/null || echo unknown)"
FINAL="/opt/satuwork/manager/releases/$VERSION"
rm -rf "$FINAL"
mv "$STAGED" "$FINAL"
# 'current' is what the systemd unit points at, and what self-upgrade swaps.
# Create then rename so the swap is atomic.
ln -sfn "$FINAL" /opt/satuwork/manager/.current.tmp
mv -T /opt/satuwork/manager/.current.tmp /opt/satuwork/manager/current
echo "    $VERSION"

echo "==> Writing config"
mkdir -p /etc/satuwork
cat > /etc/satuwork/manager.env << EOF_ENV
GATEWAY_URL=$GATEWAY_URL
SATUWORK_MANAGER_PORT=$PORT
SATUWORK_PAIRING_CODE=$CODE
EOF_ENV
chmod 600 /etc/satuwork/manager.env

cat > /etc/systemd/system/satuwork-manager.service << 'EOF_UNIT'
[Unit]
Description=Satuwork machine manager
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
# root: it creates Linux accounts, writes /etc/systemd, and starts seat units.
User=root
# Required: 'tsx' in --import is a bare specifier and Node resolves it from the
# working directory, not from the script's location. Without this, cwd is / and
# the service dies at startup with ERR_MODULE_NOT_FOUND. systemd resolves the
# symlink at start, so an upgrade picks up the new release.
WorkingDirectory=/opt/satuwork/manager/current
EnvironmentFile=/etc/satuwork/manager.env
ExecStart=/usr/bin/node --import tsx /opt/satuwork/manager/current/bin/satuwork-manager.mjs
Restart=always
RestartSec=3
# Must NOT be control-group: the seat units (slim-desktop@ / satuwork-bot@) are
# independent system units and must not die with the manager. Restarting the
# manager leaves every seat running.
KillMode=process
# 管家停机时会等在飞的席位部署脚本跑完再退（最长 20 分钟，见 manager/src/index.ts 的
# shutdown），否则脚本跑完了 commit 却没人做，席位装好了名册里没有。不忙时它 3 秒就退，
# 这个上限只在真有部署在跑时才用得到。
TimeoutStopSec=1260

[Install]
WantedBy=multi-user.target
EOF_UNIT

# The seat worker: pulls this machine's routines from the Gateway and runs them against
# the local bots (manager/src/worker/index.ts). Non-root on purpose - it holds no
# credentials of its own; it reaches the Gateway and the bots through the manager's
# loopback relay, authenticated by a per-boot token the manager writes to worker.env.
if ! id -u satuwork-worker >/dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin satuwork-worker
fi
cat > /etc/systemd/system/satuwork-worker.service << 'EOF_WORKER'
[Unit]
Description=Satuwork seat worker
After=satuwork-manager.service
Wants=satuwork-manager.service

[Service]
Type=simple
User=satuwork-worker
WorkingDirectory=/opt/satuwork/manager/current
# Written by the manager at boot; optional so the unit keeps retrying until it exists.
EnvironmentFile=-/etc/satuwork/worker.env
ExecStart=/usr/bin/node --import tsx /opt/satuwork/manager/current/bin/satuwork-worker.mjs
Restart=always
RestartSec=3
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
EOF_WORKER

# Rollback safety net for self-upgrade. The selftest only proves the new build
# starts; it cannot prove it can still reach the Gateway. That failure means an
# unreachable machine, and this architecture has no SSH left to rescue it.
cat > /etc/systemd/system/satuwork-manager-confirm.service << 'EOF_CONFIRM'
[Unit]
Description=Roll back Satuwork manager if the new version never checked in

[Service]
Type=oneshot
ExecStart=/usr/local/bin/satuwork-manager-confirm.sh
EOF_CONFIRM

cat > /etc/systemd/system/satuwork-manager-confirm.timer << 'EOF_TIMER'
[Unit]
Description=Check the Satuwork manager settled after an upgrade

[Timer]
OnBootSec=120
OnUnitActiveSec=120
AccuracySec=15

[Install]
WantedBy=timers.target
EOF_TIMER

# The rollback script ships **inside the manager package** (src/seat/manager-confirm.sh),
# not inline here. One copy, and — more importantly — the manager rewrites it from its own
# package on every boot, so a fix to it rides a normal upgrade instead of needing a
# re-install. Older packages may not carry it; keep going, the next upgrade brings it.
if [ -f "$FINAL/src/seat/manager-confirm.sh" ]; then
  install -m 755 "$FINAL/src/seat/manager-confirm.sh" /usr/local/bin/satuwork-manager-confirm.sh
else
  echo "    note: this manager package has no manager-confirm.sh; rollback safety net is off until the next upgrade" >&2
fi

# Remember what the current identity looks like before restarting. With --code,
# "the file exists" does not mean "pairing succeeded": a manager.json left over
# from an earlier pairing exists too. Re-pairing always rotates the token, so the
# file contents are guaranteed to change - that is what we wait for.
PREV_STATE=""
[ -f /etc/satuwork/manager.json ] && PREV_STATE=$(sha256sum /etc/satuwork/manager.json | cut -d' ' -f1)

echo "==> Starting"
systemctl daemon-reload
systemctl enable --now satuwork-manager-confirm.timer >/dev/null
systemctl enable satuwork-manager.service >/dev/null
systemctl restart satuwork-manager.service
systemctl enable satuwork-worker.service >/dev/null
systemctl restart satuwork-worker.service

echo "==> Waiting for pairing"
PAIRED=0
for _ in $(seq 1 30); do
  if [ -f /etc/satuwork/manager.json ]; then
    # No code: nothing should re-pair, so the file existing is the whole test.
    if [ -z "$CODE" ]; then PAIRED=1; break; fi
    if [ "$(sha256sum /etc/satuwork/manager.json | cut -d' ' -f1)" != "$PREV_STATE" ]; then PAIRED=1; break; fi
  fi
  sleep 1
done
if [ "$PAIRED" != 1 ]; then
  if [ -n "$PREV_STATE" ]; then
    # Identity unchanged: the code did not take. The manager keeps running on the
    # old identity, so the machine is not lost - but this re-pair failed, and the
    # usual reason is a code that was already used or has expired.
    echo "pairing with this code did not take; the machine kept its previous identity." >&2
    echo "The code is single use and expires in 30 minutes - generate a fresh one on the company page." >&2
  fi
  echo "Check: journalctl -u satuwork-manager -n 50" >&2
  exit 1
fi
# The pairing code is single use; no reason to leave it on disk.
sed -i '/^SATUWORK_PAIRING_CODE=/d' /etc/satuwork/manager.env
echo
echo "Paired. Machine manager $VERSION is listening on :$PORT"
echo "Deploy bots to employees from the Gateway; this machine needs no further commands."
`
}
